name: Test Coverage
description: Add or improve tests for a component or flow
labels: ["type:test", "roadmap"]
body:
  - type: input
    id: area
    attributes:
      label: Area / Component
      placeholder: e.g., Auth context login/logout; HealthCheckCard pause-on-error
    validations:
      required: true
  - type: textarea
    id: cases
    attributes:
      label: Test Cases
      placeholder: |
        - Login succeeds sets user and status
        - Logout resets user and status
        - Register handles EMAIL_EXISTS
    validations:
      required: true
  - type: dropdown
    id: release
    attributes:
      label: Target Release
      options:
        - v0.3.1
        - v0.3.2
        - v0.3.3
        - v0.4.0
        - Future
